# Generated by Django 5.2.8 on 2025-11-06 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rarity', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.cardset')),
            ],
        ),
        migrations.AddField(
            model_name='cardset',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.game'),
        ),
    ]
