# Generated by Django 5.2.8 on 2025-11-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Roxo'), ('black', 'Preto'), ('yellow', 'Amarelo'), ('multicolor', 'Multicolorido')], default='multicolor', max_length=20),
        ),
    ]
