# Generated by Django 5.2.8 on 2025-11-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='block_icon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='counter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='effect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, choices=[('leader', 'Líder'), ('character', 'Personagem'), ('event', 'Evento'), ('stage', 'Estágio'), ('navy', 'Navy/SWORD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('purple', 'Roxo'), ('black', 'Preto'), ('yellow', 'Amarelo'), ('multicolor', 'Multicolorido')], max_length=20, null=True),
        ),
    ]
